version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - '4000:4000'
    environment:
      MONGO_DATABASE: mongodb://mongo:27017/shopit
      